### ISSUE TITLE
MPVideoProcessor.m missing... cannot build project

### ISSUE THREAD

**Issue by cameronehrlich** [pppoe/MPMotionPattern#1]

**Comment by cameronehrlich** [comment]
I know that this is an old project, but I had an idea of a cool application for something like this.  Let me know if you want to discuss privately. :)

**Comment by pppoe** [comment]
Not sure when I will fix this, but that sounds interesting (:

**Comment by cameronehrlich** [comment]
Do you you have a Twitter handle? I'm @cameronehrlich
